type: object
title: ATpub Service
additionalProperties: false
properties:
  $type:
    type: string
    const: me.atpub.registry.service
  name:
    type: string
  homepage:
    type: string
    format: uri
  profileUrlTemplate:
    type: string
  identifier:
    type: object
    additionalProperties: false
    properties:
      renderFormat:
        type: string
      pattern:
        type: string
      punycode:
        type: boolean
  icon:
    type: string
  verificationMethods:
    type: object
    patternProperties:
      "^.*$":
        type: object
        additionalProperties: false
        required:
          - type
        properties:
          type:
            type: string
            enum:
              - http
              - dns
              - atproto
          input:
            type: object
          url:
            type: string
          format:
            type: string
            enum:
              - html
              - json
              - text
          selector:
            type: string
          path:
            type: string
          attr:
            type: string
          needProxy:
            type: boolean
        allOf:
          - if:
              properties:
                type: { const: http }
            then:
              required:
                - url
                - format
          - if:
              properties:
                type: { const: http }
                format: { const: html }
            then:
              required:
                - selector                  
          - if:
              properties:
                type: { const: http }
                format: { const: json }
            then:
              required:
                - path  